[green_agent]
agentbeats_id = "019bc145-7c61-7f31-b871-06a84478ead8"
env = { LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "019bc3e1-463c-7712-b376-7e71ccdcdaa3"
name = "purple_placeholder"
env = {}

[config]
