[green_agent]
agentbeats_id = "019bc145-7c61-7f31-b871-06a84478ead8"
env = { LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "019bc3da-00a0-7930-9e2d-e46dad026684"
name = "purple_agent_1"
env = {}

[config]
# assessment config (can be empty for now)
